[build-system]
requires = ["setuptools>=60.0","wheel"]

build-backend = "setuptools.build_meta"

[project]
name = "guezz_number"
version = "0.1.0"
dependencies = []

[project.scripts]
guezz_number = "guezz_number.main:main"